from pydantic import BaseModel
from uuid import UUID
from vertix.db.hylladb.model_generator.auto_generate_models import HyllaBaseModel

class UserReturn_ID(BaseModel):
    """
    An autogenerated class representing a subset of the User model.
    
    Used as a return type from HyllaDB. Allows for easy retrieval of data along with IDE support.
    
    Attributes:
    - id: `UUID`
    """

    id: UUID


class UserReturn_ID_Name(BaseModel):
    """
    An autogenerated class representing a subset of the User model.
    
    Used as a return type from HyllaDB. Allows for easy retrieval of data along with IDE support.
    
    Attributes:
    - id: `UUID`
    - name: `str`
    """

    id: UUID
    name: str


class UserReturn_ID_Email(BaseModel):
    """
    An autogenerated class representing a subset of the User model.
    
    Used as a return type from HyllaDB. Allows for easy retrieval of data along with IDE support.
    
    Attributes:
    - id: `UUID`
    - email: `str`
    """

    id: UUID
    email: str


class UserReturn_ID_Age(BaseModel):
    """
    An autogenerated class representing a subset of the User model.
    
    Used as a return type from HyllaDB. Allows for easy retrieval of data along with IDE support.
    
    Attributes:
    - id: `UUID`
    - age: `HyllaBaseModel`
    """

    id: UUID
    age: HyllaBaseModel


class UserReturn_ID_Name_Email(BaseModel):
    """
    An autogenerated class representing a subset of the User model.
    
    Used as a return type from HyllaDB. Allows for easy retrieval of data along with IDE support.
    
    Attributes:
    - id: `UUID`
    - name: `str`
    - email: `str`
    """

    id: UUID
    name: str
    email: str


class UserReturn_ID_Name_Age(BaseModel):
    """
    An autogenerated class representing a subset of the User model.
    
    Used as a return type from HyllaDB. Allows for easy retrieval of data along with IDE support.
    
    Attributes:
    - id: `UUID`
    - name: `str`
    - age: `HyllaBaseModel`
    """

    id: UUID
    name: str
    age: HyllaBaseModel


class UserReturn_ID_Email_Age(BaseModel):
    """
    An autogenerated class representing a subset of the User model.
    
    Used as a return type from HyllaDB. Allows for easy retrieval of data along with IDE support.
    
    Attributes:
    - id: `UUID`
    - email: `str`
    - age: `HyllaBaseModel`
    """

    id: UUID
    email: str
    age: HyllaBaseModel


